name: Zip Folder

on:
  push:
    branches:
      - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (for using npm install)
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install zip package
      run: sudo apt-get install zip -y

    - name: Zip the folder
      run: zip -r zipped_folder.zip polarcraft_survival_resourcepack

    - name: Upload zipped folder as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: polarcraft_survival_resourcepack
        path: polarcraft_survival_resourcepack.zip
