name: Zip and release resourcepack

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Create a zip file of the specific folder
    - name: Zip the folder
      run: |
        zip -r polarcraft_survival_resourcepack.zip polarcraft_survival_resourcepack

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: polarcraft_survival_resourcepack.zip
