name: Zip and release resourcepack

on:
  push:
    branches:
      - main  # Adjust as needed
env:
  VERSION_TAG_NAME: 1.0.0
  
jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Create a zip file of the specific folder
    - name: Zip the folder
      run: |
        zip -r polarcraft_survival_resourcepack.zip polarcraft_survival_resourcepack
        
    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: $VERSION_TAG_NAME
        assets: 'polarcraft_survival_resourcepack.zip'
        fail-if-no-release: false
        fail-if-no-assets: false
        
    # Step 3: Create a release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: $VERSION_TAG_NAME
        release_name: Folder Zip Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Upload the zip file to the release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: polarcraft_survival_resourcepack.zip
        asset_name: polarcraft_survival_resourcepack.zip
        asset_content_type: application/zip
